file:
  dir: C:\Users\qkrgy\Desktop\capstone2\src\main\resources\file\
image:
  dir: C:\Users\qkrgy\Desktop\capstone2\src\main\resources\image\

spring:
  jpa:
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/capstone2
    username: sa
    password:

logging.level.org.hibernate:
  SQL: DEBUG
  type.descriptor.sql.BasicBinder: TRACE